config/routes.rb
Rails.application.routes.draw do
  root to: "challenges#home"
  resources :challenges
  resources :responses
  resources :users, only: [ :new, :create ] do
    resources :gamerooms, only: [ :index, :new, :create, :show ] do
      post '/', to: 'gamerooms#get_blue_card', as: :grab_blue
      patch '/', to: 'gamerooms#restart_blue_cards', as: :restart_blue
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blue_card.rb
class BlueCard < ApplicationRecord
  belongs_to :gameroom
end

app/models/challenge.rb
class Challenge < ApplicationRecord
end

app/models/gameroom.rb
class Gameroom < ApplicationRecord
  belongs_to :user
  has_many :blue_cards
  has_many :white_cards
  validates :password, uniqueness: true
end

app/models/hand.rb
class Hand < ApplicationRecord
  belongs_to :user
  belongs_to :gameroom
  belongs_to :white_card
end

app/models/response.rb
class Response < ApplicationRecord
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :gameroom
  belongs_to :blue_card
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/white_card.rb
class WhiteCard < ApplicationRecord
  belongs_to :gameroom
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blue_cards_controller.rb
class BlueCardsController < ApplicationController

  def self.create_deck
    blue_db = Challenge.all
    gameroom = Gameroom.find(params[:id])
    blue_db.each do |card|
      blue_deck = BlueCard.new(content: card.text, in_deck: true, drawn: false, used: false, gameroom_id: gameroom.id)
      blue_deck.save
    end
    @blue_deck = BlueCard.all
  end

  def destroy_deck
    # destroy deck once gameroom is closed or destroyed
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  skip_before_action only: [ :home ]
  before_action :set_challenge, only: %i[show edit update]

  def home
  end

  def index
    @blue = Challenge.all
  end

  def new
    @blue = Challenge.new
  end

  def create
    @blue = Challenge.new(challenge_params)
    if @blue.save
      redirect_to challenge_path(@blue)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @blue.update(challenge_params)
    redirect_to challenge_path
  end

  private

  def set_challenge
    @blue = Challenge.find(params[:id])
  end

  def challenge_params
    params.require(:challenge).permit(:text)
  end

end

app/controllers/gamerooms_controller.rb
class GameroomsController < ApplicationController

  def index
    @gameroom = Gameroom.new
    @rooms = Gameroom.all
  end

  def new
    @user = User.find(params[:user_id])
    @gameroom = Gameroom.new

    if params[:query].present?

      @room = Gameroom.find_by(password: params[:query].to_i)
    end

  end

  def create
    # first I find the user
    @user = User.find(params[:user_id])
    # I create the game room and make sure is created
    @gameroom = Gameroom.new
    until @gameroom.save do
      @gameroom.user = @user
      @password = rand(6 ** 6)
      @gameroom.password = @password
      @gameroom.save
    end
    # creating the blue deck of the room and getting the info from the DB
    blue_db = Challenge.all
    blue_db.each do |card|
      blue_deck = BlueCard.new(content: card.text, in_deck: true, drawn: false, used: false, gameroom_id: @gameroom.id)
      blue_deck.save
    end
    # creating white deck of the room and getting the info from the DB
    white_db = Response.all
    white_db.each do |card|
      white_deck = WhiteCard.new(content: card.sentence, in_deck: true, in_hand: false, drawn: false, used: false, gameroom_id: @gameroom.id)
      white_deck.save
    end
    redirect_to user_gameroom_path(@user, @gameroom)
  end

  def show
    @user = User.find(params[:user_id])
    @gameroom = Gameroom.find(params[:id])
    @blue_deck = BlueCard.all.where(gameroom_id: @gameroom.id).and(BlueCard.all.where(in_deck: true))
    @blue_drawn = BlueCard.all.where(gameroom_id: @gameroom.id).and(BlueCard.all.where(drawn: true))
    @white_deck = WhiteCard.all.where(gameroom_id: @gameroom.id)
    if @blue_deck.empty? && @blue_drawn.count < 1
      @text = "Start over the game"
    else
      draw_card = BlueCard.find_by(drawn: true)
      if draw_card.nil?
        @text = "Que empiece el desvergue"
      else
        @text = draw_card.content
      end
    end
  end

  def get_blue_card
    @user = User.find(params[:user_id])
    @gameroom = Gameroom.find(params[:gameroom_id])
    @blue_deck = BlueCard.all.where(gameroom_id: @gameroom.id).and(BlueCard.all.where(in_deck: true))
    # @white_deck = WhiteCard.all.where(gameroom_id: @gameroom.id)
    card_in_deck = BlueCard.find_by(drawn: true)
    if card_in_deck.nil? == false
      card_in_deck.drawn = false
      card_in_deck.used = true
      card_in_deck.save
    end
    last_card = @blue_deck.count
    index = rand(1..last_card)
    draw_card = @blue_deck[index - 1]
    until draw_card.in_deck
      index = rand(0..last_card)
      draw_card = @blue_deck[index]
    end
    draw_card.drawn = true
    draw_card.in_deck = false
    draw_card.save
    redirect_to user_gameroom_path(@user, @gameroom)
  end

  def restart_blue_cards
    @user = User.find(params[:user_id])
    @gameroom = Gameroom.find(params[:gameroom_id])
    @blue_deck = BlueCard.all.where(gameroom_id: @gameroom.id).and(BlueCard.all.where(used: true))
    @blue_deck.each do |card|
      card.in_deck = true
      card.drawn = false
      card.used = false
      card.save
    end
    redirect_to user_gameroom_path(@user, @gameroom)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  before_action :set_response, only: %i[show edit update]

  def index
    @white = Response.all
  end

  def new
    @white = Response.new
  end

  def create
    @white = Response.new(response_params)
    if @white.save
      redirect_to response_path(@white)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @white.update(response_params)
    redirect_to response_path
  end

  private

  def set_response
    @white = Response.find(params[:id])
  end

  def response_params
    params.require(:response).permit(:sentence)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to  new_user_gameroom_path(@user)
    else
      render :new
    end
  end

  def destroy
      #destroy user after 24 hrs...how?
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/white_cards_controller.rb
class WhiteCardsController < ApplicationController
  def self.create_deck
    white_db = Response.all
    white_db.each do |card|
      white_deck = WhiteCard.new(content: card.sentence, in_deck: true, in_hand: false, drawn: false, used: false)
      white_deck.save
    end
    @white_deck = WhiteCard.all
  end

  def destroy_deck
    # destroy deck once gameroom is closed or destroyed
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blue_cards_helper.rb
module BlueCardsHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/gamerooms_helper.rb
module GameroomsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/white_cards_helper.rb
module WhiteCardsHelper
end

app/views/challenges/create.html.erb
<h1>Challenges#create</h1>
<p>Find me in app/views/challenges/create.html.erb</p>

app/views/challenges/edit.html.erb
<h1>Challenges#edit</h1>
<p>Find me in app/views/challenges/edit.html.erb</p>

app/views/challenges/home.html.erb
<div class="home">
  <div class="container">
    <div class="row cards">
      <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12 card">
        <%= image_tag "Logo en blanco.png", class: "logo" %>
      </div>
      <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12 start-line">
        <h3>Que empiece el desvergue!</h3>
        <%= link_to 'Comenzar', new_user_path, class: "btn btn-ghost", id:"start-btn" %>
      </div>
    </div>
  </div>
</div>

app/views/challenges/index.html.erb
<h1>Challenges#index</h1>
<p>Find me in app/views/challenges/index.html.erb</p>

app/views/challenges/new.html.erb
<h1>Challenges#new</h1>
<p>Find me in app/views/challenges/new.html.erb</p>

app/views/challenges/show.html.erb
<h1>Challenges#show</h1>
<p>Find me in app/views/challenges/show.html.erb</p>

app/views/challenges/update.html.erb
<h1>Challenges#update</h1>
<p>Find me in app/views/challenges/update.html.erb</p>

app/views/gamerooms/new.html.erb
<div class="container">
  <h3>Create a Gameroom to play with your friends!</h3>
  <%= simple_form_for [@user, @gameroom] do |f| %>
    <%= f.error_notification %>
    <div class="form-actions">
      <%= f.button :submit, "Create Room", class: "btn btn-ghost", id:"start-btn"%>
    </div>
  <% end %>
  <h3>Or join an existing room</h3>
  <%= form_tag new_user_gameroom_path(@user), method: :get do %>
    <%= text_field_tag :query,
        params[:query],
        class: "form-control col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3",
        placeholder: "Find a Room"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  <% if @room.nil? %>
    <h4>Room not found</h4>
  <% else %>
    <%=@room.user.name%>'s room found <%= link_to 'Join', user_gameroom_path(@user, @room), class: "btn btn-ghost", id:"start-btn" %>
  <% end %>
</div>

app/views/gamerooms/show.html.erb
<div class="container">
  <h3>Room Token:</h3><strong><%=@gameroom.password%></strong>
<h4><%= @gameroom.user.name %>'s room</h4>
<br>
<%# <% blue_deck.each do |card| %>
  <%# <% card.content %>
  <%# <br> %>
<%# <% end %>

<% if @blue_deck.empty? %>
  <h1><%= @text %></h1>
  <%= link_to 'start over', user_gameroom_restart_blue_path(@user, @gameroom), method: "patch", class: "btn btn-ghost", id:"start-btn" %>
<% else %>
  <h1><%= @text %></h1>
  <%= link_to 'Grab a blue card', user_gameroom_grab_blue_path(@user, @gameroom), method: "post", class: "btn btn-ghost", id:"start-btn" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <h3>First create a Player</h3>
   <%= simple_form_for( @user ) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" }%>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Create User", class: "btn btn-ghost", id:"start-btn"%>
    </div>
  <% end %>
</div>